Repository TKONIY/Canteen-Info-System, pull requests merged in 2019-11, with the labels that each got.

#5 添加团队合作教程pdf
  docs/materials/GitHub-teamwork-tutorial.pdf
Labels: documentation

#7 Update README.md
  README.md
  docs/materials/GitHub-teamwork-tutorial.pdf
Labels: documentation, learn

#16 更新第一次会议的文件
  README.md
  docs/conference/conference-1-record.pdf
Labels: conference, documentation
